sass:
  style: compressed

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-sitemap

name: Simon Schwartz

permalink: pretty

url: # add site url
